# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "dwc3_pci" "usb_storage" "sd_mod" "sdhci_acpi"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/73553314-d84b-495f-925e-038445a1fa7c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6E73-25F0";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/a3c6ed03-3c01-4168-a8b6-67ebd3e89fac";}];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
