#!/usr/bin/env bash
project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "${project_dir}/ci/common.sh"

computer_name=$1

export NIX_PATH=nixpkgs=$project_dir/nixpkgs
export NIX_PATH=$NIX_PATH:nixos=$project_dir/nixpkgs/nixos
export NIX_PATH=$NIX_PATH:nixos-config=$project_dir/computers/$computer_name/configuration.nix

nix="$(nixos-build-cache-result-path config.nix.package.out)"
system="$(nixos-build-cache-result-path system)"
ln -s "${system}" $project_dir/../latest
