#!/usr/bin/env bash
set -ex
project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "${project_dir}/ci/common.sh"

computer_name=thrash

export NIX_PATH=nixpkgs=$project_dir/nixpkgs
export NIX_PATH=$NIX_PATH:nixos=$project_dir/nixpkgs/nixos
export NIX_PATH=$NIX_PATH:nixos-config=$project_dir/computers/$computer_name/configuration.nix
export NIX_PATH="${NIX_PATH}:nixpkgs-overlays=${project_dir}/nixpkgs-config/overlays"

nix="$(nixos-build-cache-result-path config.nix.package.out)"

cd "$project_dir"

$nix/bin/nix-build . --out-link thrash-image --attr image
