#!/usr/bin/env bash
set -ex

config_dir=$WORKSPACE/nix_configs

export NIX_PATH=nixpkgs=$config_dir/nixpkgs
export NIX_PATH=$NIX_PATH:nixos=$config_dir/nixpkgs/nixos
export NIX_PATH=$NIX_PATH:nixos-config=$config_dir/computers/$1/configuration.nix
nixos-rebuild build
