#!/usr/bin/env bash
set -e
source /etc/profile

config_dir=$WORKSPACE/nix_configs

export NIX_PATH=nixpkgs=$config_dir/nixpkgs
export NIX_PATH=$NIX_PATH:nixos=$config_dir/nixpkgs/nixos
export NIX_PATH=$NIX_PATH:nixos-config=$config_dir/computers/agh/configuration.nix

set -x

exec nixos-rebuild --show-trace build
