#!/usr/bin/env bash
# build_with_overlays nixpkgs-path nixpkgs-derivation

set -e
source /etc/profile

nix_configs_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "${nix_configs_dir}/ci/lib.sh"

src_dir="$1"
attr="$2"

set -ex
nixos-test-cache-result-path "${src_dir}" "${nix_configs_dir}/overlays" "${attr}"
