# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports = [ <nixos/modules/installer/scan/not-detected.nix>
            ];

  boot.initrd.availableKernelModules = [ "xhci_hcd" "ehci_hcd" "ahci" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/boot" =
  {
    device = "/dev/sda1";
    fsType = "ext4";
    options = [ "rw" "stripe=4" "data=ordered" "relatime" ];
  };

  nix.maxJobs = 4;
}
